# Generated by Django 4.2 on 2024-04-26 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название товара')),
                ('price', models.PositiveIntegerField(verbose_name='цена товара')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='фото товара')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время создания объявления')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст отзыва')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время написания отзыва')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_ad', to='ads.ad', verbose_name='объявление, под которым оставлен отзыв')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
